.TH contractor 1 "May 27, 2014"
.SH NAME
contractor \- service for sharing data between apps
.PP
\fBcontractor\fP is a sharing service that allows source apps to
send their data to registered destination apps. This way,
data source apps don't have to have the destination apps hard-coded into them.
.SH SYNOPSIS
.B Do not invoke this command directly. Contractor is accessed via a D-bus interface.
.SH AUTHOR
contractor was written by ammonkey <am.monkeyd@gmail.com>,
Corentin Noël <corentin@elementaryos.org>,
Akshay Shekher <akshay@elementaryos.org>,
Michael Lazarski <michael@lazarski.me>,
Sergey "Shnatsel" Davidoff <sergey@elementaryos.org>,
Victor Martinez <victor@elementaryos.org>.
.PP
This manual page was written by Sergey "Shnatsel" Davidoff <sergey@elementaryos.org>,
for the Debian project (but may be used by others).
